export interface Stats {
    playerId: number,
    name: string,
    img: string,
    currentTeam: string,
    age: number,
    height: string,
    weight: number,
    exp: number,
    college: string,
    year: number,
    team: string,
    gp: number,
    points: number,
    rank: number,
    att: number,
    rushYd: number,
    rushYpc: number,
    rushTd: number,
    tar: number,
    rec: number,
    recYd: number,
    recYpt: number,
    recYpc: number,
    recTd: number,
    fum: number,
    lost: number,
}