export interface RunningBack {
    rbId: number,
    rank: number,
    name: string,
    team: string,
    byeWeek: number,
    points: number,
    rushAttempts: number,
    rushYards: number,
    rushTds: number,
    recs: number,
    recYards: number,
    recTds: number,
    fum: number,
    fumLost: number,
    firstDowns: number,
    hundredGame: number,
    twoHundredGame: number,
    fourtyPlay: number,
    fourtyTd: number,
    passComp: number,
    passYards: number,
    passTds: number,
    targetShare: number,
    pointsGame: number
}